os: osx
osx_image: xcode11
language: swift
install:
- sudo gem install xcpretty-travis-formatter
script:
- xcodebuild -workspace Datastore.xcworkspace -scheme Datastore test | xcpretty-travis-formatter
notifications:
  email: false
  slack:
    rooms:
      secure: VY98dlPexEIbCLMvucp9q7Qt/jOnAyntKfSEPXNdfAsdFKQfMwFUqUZ3v9ePj2RRh+vRdd7+ip1kn6cR5sQwc7Bn+HUIJVE6X1Z4BVKYYQH/5O12gXlvDnNIB2tFGVK7jPIPABNb+XtH5XLeLhAHqIBZZpQz+9ZZoJmKJ22fXqof/a+9dLFGu4o0J2ckuaQjpAXsg8ZSTp+Vvg2JrgrEkRpvuTq5zwBPHub9ZlYSNveIjKXHThZrL8v6TgzLc4eF/p/2t5Wj0ZEs3r+ashLkoXO1kuwMqx0pNYxgUL1HnItO3bf03RNurpGX6BUqIDoq4GMTxmufOoPbE+gXov2RxRTC5ujtMvsLuAfuOxF/pJNRpmeo43GVaQtfq4DRA2bcg1/zsa7fMRJ5qC08QmimjBNzQSGAfaGaigP3apt1DliCT3SNWMAGq4jV+0e9AnSECErPgpXYOSAFScP5c0iqp3nkH1lqFTlHRBnk3m4qHKuaQkmEJQUac1+4kf8DJSgZyesoldXYKd3zbAu/wx7h12q/N57AE4Vbijowcak7dc3Tf/QR3mnHNXDW/3/X7glIyWwUhJHaQEK6oihvY1R2CiTlHAtuoBInzJogZlZleV7N+U3MJ77glm6khDLrNkByc7r90gMyE6ZFb1+4Abc+BGYlahqJiGiNpZU86p187IE=
